name = "hello"
main = "worker/index.js"
compatibility_date = "2026-09-16"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "farasdanga-db"
database_id = "64bf5903-2047-4a62-afa7-eb261897c18c"

[vars]
SITE_URL = "https://hello.farasdanga.workers.dev"
